#:kivy 1.8.0

<SpecialButton>:
    canvas:
        Color:
            rgba: 1.0, 0.0, 0.0, 1.0
        Rectangle:
            pos: self.pos
            size: (self.size[0]/4, self.size[1]/4)



<button_press>
    Button:
        id:"ok_button",
        text:"OKK",
        font_size:"20sp",
        background_color:(1, 1, 1, 1),
        color:(1, 1, 1, 1),
        size:(32, 32),
        size_hint:(.25, .1),
        pos_hint:{'x': .38, 'y': .3}
        #on_release:root.sure_input()
        #on_press: root.state_changed()